---

- name: mkdir backend
  become: true
  command: mkdir -p /home/ubuntu/udapeople

- name: Copy files from backend
  become: true
  synchronize:
    # src: /project/backend/dist
    src: "{{ inventory_dir }}/../../backend/dist"
    dest: /home/ubuntu/udapeople

- name: Copy files from backend
  become: true
  synchronize:
    src: "{{ inventory_dir }}/../../backend/node_modules"
    dest: /home/ubuntu/udapeople

- name: "install pm2"
  become: true
  command: 
    - apt update
    - apt install nodejs
    - apt install npm
    - npm install pm2 -g
  args:
    chdir: /home/ubuntu/udapeople/dist

- name: "start server"
  become: true
  command: pm2 start -f ./main.js
  args:
    chdir: /home/ubuntu/udapeople/dist