---

- name: mkdir backend
  become: true
  command: mkdir -p /home/ubuntu/udapeople

- name: Copy files from backend
  become: true
  synchronize:
    src: /home/backend/dist
    dest: /home/ubuntu/udapeople

- name: Copy files from backend
  become: true
  synchronize:
    src: /home/backend/node_modules
    dest: /home/ubuntu/udapeople

- name: "start server"
  become: true
  command: pm2 start -f ./main.js
  args:
    chdir: /home/ubuntu/udapeople/dist